export enum ErrorCode {
    // Validation Errors
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    INVALID_INPUT = 'INVALID_INPUT',

    // Authentication Errors
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
    TOKEN_EXPIRED = 'TOKEN_EXPIRED',
    INVALID_TOKEN = 'INVALID_TOKEN',

    // Resource Errors
    NOT_FOUND = 'NOT_FOUND',
    RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',

    // Business Logic Errors
    BUSINESS_ERROR = 'BUSINESS_ERROR',
    CONFLICT = 'CONFLICT',
    DUPLICATE_ENTRY = 'DUPLICATE_ENTRY',
    INVALID_STATE = 'INVALID_STATE',

    // Database Errors
    DATABASE_ERROR = 'DATABASE_ERROR',
    UNIQUE_CONSTRAINT_VIOLATION = 'UNIQUE_CONSTRAINT_VIOLATION',
    FOREIGN_KEY_VIOLATION = 'FOREIGN_KEY_VIOLATION',

    // Permission Errors
    INSUFFICIENT_PERMISSIONS = 'INSUFFICIENT_PERMISSIONS',
    SELF_ACCESS_REQUIRED = 'SELF_ACCESS_REQUIRED',

    // Rate Limiting
    RATE_LIMITED = 'RATE_LIMITED',

    // Business Specific
    LEAVE_BALANCE_INSUFFICIENT = 'LEAVE_BALANCE_INSUFFICIENT',
    PAYROLL_ALREADY_EXISTS = 'PAYROLL_ALREADY_EXISTS',
    INVALID_LEAVE_STATUS = 'INVALID_LEAVE_STATUS',
    MANAGER_HIERARCHY_ERROR = 'MANAGER_HIERARCHY_ERROR',
    HIRE_DATE_FUTURE = 'HIRE_DATE_FUTURE',
    PAYROLL_PERIOD_OVERLAP = 'PAYROLL_PERIOD_OVERLAP',
    INVALID_TIME_RANGE = 'INVALID_TIME_RANGE',
}
